os: linux
dist: trusty
group: stable
sudo: required

language: java
jdk: openjdk8

services:
  - docker

env:
  global:
    - PROJECT_VERSION=0.0.1
    - NODE_VERSION=10.6.0
    # ARTIFACTORY_USERNAME
    - secure: ldlkDhRSNvMd4ZZAMBAl/BAPd/uPJEI5kSFW5RkKVFHmmXgGE49+Qu7NrySuG9gC0hxUu0s8nHeLCTajz3ovbhDZ6psHRfIofieIbVljdtfEtdSzWQx2BD4M3PWUe7/DLNth/Z/vWmfXnNUI/XMb+KUNOlaed8vLmb+V4zdI2Vt/S47rB8ndZH/k4p2kufAuYWekXDrb8VdiCFt1zrVvvp7Tls6Aj/x8737XJ01dQfVsJX/XsCmEPUHaHOeQD6f5aK1RtrkQsz5yKtZL5Zu9Q9jYUl7Dt5SU8YDZHLc6iGgXVjrafuK7ywLf6JmZYnNCR2TxzDCYx9RokkxX3JvBhcN/JrG+1M43S0azzNn3tjKZa+tZnvzmBq5w+Nbi/XxsTBUa2XA0sXuEXDVGWaW5r9sArd/onkQYIJjZq+N/nwwoVekL7FzckLjCc/yxKa4ddvSKoZIfq9tADZ9KAKcGQspCO5VsySOptCQE/nwOLYSL4Z3+MvOI+C6204JK1d3t2SfW5WRe74uLGEcHwTh84l+QG6ioEOlCEBD8nKq/whLJ2sPCfSxpp6e0Iid59p+cbGPtRoav9GVfZgp1eDbV6R6J2mQwBrGbNvnaOr/eprsAT7ukoJ+Pw2DEGmlLKF/Vr9bxDMrzJJCfLzcOzG5W3ZrfsVe67BnHD8caMrdoofs=
    # ARTIFACTORY_PASSWORD
    - secure: lcl4Xg7NCssLCJ5xUtUJ5726m3Xmtdl72ZTCU6p26+d3UuG0XapuYbBT2l52JdjJyD21hDxVLfHhm5hV1dHFLzULIJZQsCLT80saL1gH2e/nYNiivwqZL6BN5+Yv4RmD1L/mAZZFzuu6plUHoEIurl6Pw9dv93spKuQCR1N6Gju3ktfMY/8pWtbmDAk/oMEhowj1Vg5x9ehlADSAPur14z36uJtI37eEOK63XFuQJUi4GylAhDLroaaZSORljJ3IsNI3nGIrDVRrnVLlrWuhRhB4HCl6FUqwgDgVWAKDB6+K+dE6Nx7HiUP0RVT3Nr61I/8JfrViUnJ4mSO84/sI62/Cs8trPvIJjK5AvohecbMkUAB0LD43xCFiAvaMx8XSiC4MPisDkZuhZuYWNXeu/C8zrx5xvF7lzifGIhk2zLbBLRkuGZNlQhR4ILpqa6JeC3lF7mq6ur2e3zWm7bMpudF5sFslCBFN4o6XHJPXmxmjx6k/IhZu6xYujTiePqMGCX+DAcw/3QEF/so0Tb2I5vo61WUwxtBBXBkGsRIYtLg9GWlLRCvypIocqfxQM1GhgnAfIYLo9v+dj7vpkmtHqd86kXjzBgFq8leXd032AXK+IEFuFLv5avA8BR4oECBRXFvr3/aI+xBeV/md/SNp1oPTLCY3jRyUA0QeC6RmheU=
    # GIT_USER
    - secure: Tir8nfYtt9PKu+sdMXbtlBT9cVqaixUIpflSfb4pU/B/7XGWbxKSuy/rbxdCnrNyC/jtlAfGWk8HQu1zPuPPdDZlEj8p1FuwcXb2LVo48zIywA07hoA2z7iuANpqrmSgZxEDFuJRzdqkhUDUZSXGMYgHdDAOl7qUnlwfFKMM9/up9h2YD64SUY6y7xlF0jq3tf5SyIFvcQmtC2u0uIHrOThXBmTqrlhEummNRvh/YGHHJzJBLEfArkfihxyYiKbcy+mqZM3j3LYTRTtZCYVb/zXvW0c9ng1nf3eOsF1qFwyJ2jTrSm1KRMdT+Lv79W6qB17Dxi9EmwlQWcw2p7c8HMpEZTvURGcft6W1mNOG2d08zUY+s/20uJJ7Z1gg4A6e1PL+U7DKN3ehBzbtXnN0Y6SvNqsPfPdOTa06ywGmF+Z8EElgssbxTBuTymwnlZVmaVM+DWZw2/+jBCyd4TUJHrQ3/erdii0NvaSEb9kCkbgkunoFJ3tmQa+Gmq1AWBZue+Eh/D9BqWol2FxRGP9UjQja8+xg+il47SdMPSlgqcdNTyiWYCmH1X9mpRGLa6+nhNh71D6K+4qHEAuSLhPdLeP3Fe8K97QqPxv0Pc2QRRKxRjk2z1aZZF/iejrFOP/zbHs9X0PdmhmLqfmygUh4IbRqW3iFABkopLcweE9xHDM=
    # GIT_PWD
    - secure: Jw2UtfhgNX6cBJ0bKTNtx4I4+CCZAw8dWhBvX8IkxIqCxf+Pc9Mxf4zkoSJwqDe2uWaGLtKJtThj5RGRv/nsqM2F1brGOtwe0OcslAxhJenr9vvI1rsG1Z7LnpHYv6vMqbZ5tzEN3+6vxvy3P0uycCVPoC/C1rJp5arguxDJXqiDRvWJuUEriubqojl0FdZMFkyNIM7NkFkutC9ggWdvXO5gaDXwZeF/eD9bAA00VYvaONNVBrMiGFTElUEooMDfLrdkwzq4QxN8yhSxKHC0avct3YUy8VV3Feazp0VXw5W0iLC9xZmdgmA0DJnS9pmAdlM+APYQTkGtapoh7JnThseMJfvmXy1zQXI9io5m0x+0l52SnV9kU4qo0Y9vo8wKGr64WrcfUx7og4M+j5OcUhoyVm9Qu+RioOFCUSWmznR0Q9WwLjm7KJLZULvz2QVlvvgZRd2h/UNnSJhIfZ1PxjPE4inDfOaYXZVVVaZTmHF/iTdtnLQ8x8wWW22CQ0Kdvq2BOQ79uktKm/MtuIJ7EYj+VIhAwBegkPuUIJa1xsohvgJ7ESQD/9794g3q1dQvCTY9kQYD+7nay8JQyZ1yT5DsoYBwdQ3VujpJ/DCpRhRp1N/8K1t3V93KKZDY2sSs3tgTOfwW7lmHAyNAVUT6THszAiCP17MAQ81x9IfTgE8=

before_cache:
  - rm -rf $HOME/.m2/repository/ch/admin/seco/alv-portal-*

cache:
  directories:
    - $HOME/.m2
    - alv-portal-ui/node_modules

install:
  - .ci-travis/install-nodejs.sh ${NODE_VERSION}
  - .ci-travis/install-chrome.sh

script:
  - export BRANCH_VERSION_SUFFIX=$([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo "-${TRAVIS_BRANCH//\//-}")
  - export BUILD_VERSION=$PROJECT_VERSION-build-$TRAVIS_BUILD_NUMBER$BRANCH_VERSION_SUFFIX
  - .ci-travis/build.sh ${BUILD_VERSION} ${TRAVIS_BRANCH} ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
  - .ci-travis/deploy-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}
