os: linux
dist: trusty
group: stable

language: java
jdk: openjdk8

env:
  - NODE_VERSION=10.6.0 CHROME_VERSION=67.0.3396.99-1

before_install:
  # install nodejs
  - nvm install ${NODE_VERSION}
  - node -v
  - npm -v
  # install chrome
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable=${CHROME_VERSION}
  - google-chrome --version

script:
  - ./mvnw clean install
