os: linux
dist: trusty
group: stable
sudo: required
language: java
jdk: openjdk8
services:
- docker
env:
  global:
  - PROJECT_VERSION=0.0.1
  - NODE_VERSION=10.9.0
  - secure: ZTaGCqbM4hReM1T2w9pURLYvOpNsTe/hiReJ86uZUqRkDzptEstFa/VSXpfBqInLvyuzS0UDEIbljBXdYLIyFFXwA6Zfa0kKmObCed8oDPPO09uO8rHqqvccdmMhKGf/UPO8yoHJViBZad00pOK6kQJHVcuav9Oenskkn4cE+eAg2D7FB12gRjShnI/NFf2t1lLwna2o2uhcSGrT4mOqm8U+ygjmjbmoXrc0fdl/3jh+0uV+G2PzLDO30B4AswVoCI0Wvg0/lALL/vQxggadTm4A61rUMvKVB3UmKrFVwp1Cza6B35+gSadYWOl+b/uC9qfmy8sG7CFxqYc/1jwGorZXGxGKC1Mh4OpZv6tbRokoQX4BZUU4XK687GsGZsDqGgM613r6i6K2NsXsKRpI3v6tuM+qeqiuh7tzYkxJgdPXZYlJ62kHdP+AqhNzFUusBWkhcUftvEb8sBMB1kCLLOhQV0NwQundDnaYGT8Tu13hgE+/cXvWbVqRfLPEUhY/xVMxjQF3PxXP9XG26j543aZEQy/udUTIeSkb8oHTI6RNBygCqgp+EU4xTJuWF678Yza139lcTs1luoxSZGqmmj7yiKEnzNerKVrraUkVZuQB0uWoUVx7lhAj6YHMHZcyOsxIFU2YYFwYazBytir5UZQFFONJyDc9hb9r7CY03WM=
  - secure: Dp92d/WvgpAuH1HuhfpxLyU9LBsfN5vLeRIazKdCNHUY4/uiScSlByzPB8Q81qgwwjCFIBcXF5H5o3BQ6zEafCpBoU6TCfX7zLPfT1ve7HD6iIFBLlwNWEEi1RDykH3Q3Fq3hXp1R3qaDwmkTSSHcxTAv5Faa9ITpviOkK6bErJEs0Y2wrOCj/TscjFbf/ayrigHAQ3JjEWBn4Wp3pHpC2axdWjYxWwf7OSHeXxcI+GZ1oNP+bCAgdB4+ufktkgMF2Vz9V2LIb/rmccXtgjRY6YFsZ0wXToX9yiW1DhTz3J1kHtboLk1RHDABJonOBVqmPalH/cUpOPEd3BUXxK2wcp78gRIEV70kdcwZ5BwukXw9sL19g1Vx1Qbwrwp7BzoJm6W4a9NR6x7rskdRuqu1BZQ50SByURcfWIY0zUBtvgfWdH9rrgVjMCkcaSgXHr9KClNWfEbLyAmRehcayZcZ+RURQfKNe9hvSeeP1UGoPp+IUcwG9oI1BZnrZJ3zxMCvg6VNxPno+Zk/aFUujv40Tx82v9PnfTl3EM8Oe3cIKxpmFTkHq73uockc1PQSeevUchfdO39mV9Hce5iIUz8VdmW8KaZpiRwnX8v4KYrlnJa8K+3UcgH4tPFj7aOSeX/hkCpbDORWJcUXC3kI9Zw9lPWO0PfA+axB6EeqXoBNys=
  - secure: MxW/fMRzPm9tbAPr9/G9piK/iTxI2ILtAqZZjsTu5ilzzEdMwA90gQhmO/lN0LI1Rw+Oqp3WXuR/HHQMMfajYnDui2BjyeHYUcyUBNyaUk0p3HzhO9GvbtQiXGDHJBbjkuK0TKlGiFUvSs1WwBTEvVeZQaxVpPNSZHDlT6zBKMl3IC8Dvx12397GXJODNIFCbXL6irXB2qhCO06zjpjVjJ90wL+ftjsh8R3VnyVSKOPRQKEmlNko48IFzKIWvH+j3of94hmlgeEdYtVpSEyir4AGSA4+gkxtLxCVH453ey+8CcAAaQPPCkEhKLdtoph/+Oxq1dbRRhGWB7Yi7K0gyF9noJl2UEUrzyZ2PYn1h6H/bSvh6vEkLp4lAKyz/L5WroYhcLuOLB/HbdoVvNBwBN/J16W2dAJSx6j9bPo+fBwo1y/kqnmZWTse3gnQx/HanSPZODCSHCaVBrkk3aNVdgjNJYAoXG5A6CsXJbM4Kj8NjG1R7EykxZ2lR+iD375TN1QHdNIMbvRs8IplycGrfan0Tk5BlDo7CDdOY81MpKT/2lV1NZ03IbQ+bJ/tXwNyfaLClfMmcvpw2KLsIu3PGY3QEISDAq03HoUrbRbDnz4o8A/yIVcFsgLhdYGK1FuzmOn63DhuoSzI9D1o4lmZ0xlAax+Bc6kq4zIg4ZNOz+w=
  - secure: bTMhWD7fW/aIobh6LJyy5TTQctcvW3DyQBLC4lKLs5eOnr1UzDjznyIVaOjvG7uWLmny3e/DWUiN7vUhEvJKrkjmuldIoinxUvFJOWl3m2G828RAdRgiB8Ys7SI0VppPh/KNGvsTIppl5cn6IwMjKLY2Be/Wyf+5sIv++pN7Yp05Vb3pdTcVqKALKVgQZMFnka1yWAmyHoOaN459Ayeaw1rxPyZcypYI8/zPnPnZeujRStP6AUxeJ5iGnyj4sGCTLXaBY7O+j58uQfw8DE1YRQswiP2reEJc4P5spKMlNxR00rx8V/JRE8samKdDw42ct0yB57lxAWgxiaaEHgvKqs1IFr8VxzXBb5Wiv/q9gFN3QbpAIb0GCM8iX1UC5gV90BeptDozyME/6Vn9MQt6Vh7o1MZoqHfOseg8wnQ1eS/tlRWasmhNDB3eALFNuwQG1xg7KBgMzS254jkPkyF0s38hke6Ga/TIrUfY2PQKTORzVYkhN+GP9xUq5/G1BpZRD0REQckQSJW9jn4RTctm7UlqABYHMRfS2pf2TzeFIH3LKs1V4wBTAZbvmFPAzdc6Rz/R+UYYR8Bc90SgTBq2nPCXDOMtemnWbxmqll6La8xKK2c/eoTfH9LhKaApMfF08M+xzxgFUU+IWoovv/+5uRl+wVXL2Op7u9QkUg6fXxA=
before_cache:
- rm -rf $HOME/.m2/repository/ch/admin/seco/alv-portal-*
cache:
  directories:
  - "$HOME/.m2"
  - alv-portal-ui/node_modules
install:
- ".ci-travis/install-nodejs.sh ${NODE_VERSION}"
- ".ci-travis/install-chrome.sh"
script:
- export BRANCH_VERSION_SUFFIX=$([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo
  "-${TRAVIS_BRANCH//\//-}")
- export BUILD_VERSION=$PROJECT_VERSION-build-$TRAVIS_BUILD_NUMBER$BRANCH_VERSION_SUFFIX
- ".ci-travis/maven-set-version.sh ${BUILD_VERSION}"
deploy:
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-package.sh"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^release.*$"
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-e2e.sh"
  on:
    all_branches: true
    condition: "$TRAVIS_EVENT_TYPE == cron"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
