os: linux
dist: trusty
group: stable
sudo: required
language: java
jdk: openjdk8
services:
- docker
env:
  global:
  - PROJECT_VERSION=0.0.1
  - NODE_VERSION=10.9.0
  - secure: ZTaGCqbM4hReM1T2w9pURLYvOpNsTe/hiReJ86uZUqRkDzptEstFa/VSXpfBqInLvyuzS0UDEIbljBXdYLIyFFXwA6Zfa0kKmObCed8oDPPO09uO8rHqqvccdmMhKGf/UPO8yoHJViBZad00pOK6kQJHVcuav9Oenskkn4cE+eAg2D7FB12gRjShnI/NFf2t1lLwna2o2uhcSGrT4mOqm8U+ygjmjbmoXrc0fdl/3jh+0uV+G2PzLDO30B4AswVoCI0Wvg0/lALL/vQxggadTm4A61rUMvKVB3UmKrFVwp1Cza6B35+gSadYWOl+b/uC9qfmy8sG7CFxqYc/1jwGorZXGxGKC1Mh4OpZv6tbRokoQX4BZUU4XK687GsGZsDqGgM613r6i6K2NsXsKRpI3v6tuM+qeqiuh7tzYkxJgdPXZYlJ62kHdP+AqhNzFUusBWkhcUftvEb8sBMB1kCLLOhQV0NwQundDnaYGT8Tu13hgE+/cXvWbVqRfLPEUhY/xVMxjQF3PxXP9XG26j543aZEQy/udUTIeSkb8oHTI6RNBygCqgp+EU4xTJuWF678Yza139lcTs1luoxSZGqmmj7yiKEnzNerKVrraUkVZuQB0uWoUVx7lhAj6YHMHZcyOsxIFU2YYFwYazBytir5UZQFFONJyDc9hb9r7CY03WM=
  - secure: Dp92d/WvgpAuH1HuhfpxLyU9LBsfN5vLeRIazKdCNHUY4/uiScSlByzPB8Q81qgwwjCFIBcXF5H5o3BQ6zEafCpBoU6TCfX7zLPfT1ve7HD6iIFBLlwNWEEi1RDykH3Q3Fq3hXp1R3qaDwmkTSSHcxTAv5Faa9ITpviOkK6bErJEs0Y2wrOCj/TscjFbf/ayrigHAQ3JjEWBn4Wp3pHpC2axdWjYxWwf7OSHeXxcI+GZ1oNP+bCAgdB4+ufktkgMF2Vz9V2LIb/rmccXtgjRY6YFsZ0wXToX9yiW1DhTz3J1kHtboLk1RHDABJonOBVqmPalH/cUpOPEd3BUXxK2wcp78gRIEV70kdcwZ5BwukXw9sL19g1Vx1Qbwrwp7BzoJm6W4a9NR6x7rskdRuqu1BZQ50SByURcfWIY0zUBtvgfWdH9rrgVjMCkcaSgXHr9KClNWfEbLyAmRehcayZcZ+RURQfKNe9hvSeeP1UGoPp+IUcwG9oI1BZnrZJ3zxMCvg6VNxPno+Zk/aFUujv40Tx82v9PnfTl3EM8Oe3cIKxpmFTkHq73uockc1PQSeevUchfdO39mV9Hce5iIUz8VdmW8KaZpiRwnX8v4KYrlnJa8K+3UcgH4tPFj7aOSeX/hkCpbDORWJcUXC3kI9Zw9lPWO0PfA+axB6EeqXoBNys=
  - secure: RI8RYLHoftqatqx9/rRQn++Iu3bS8KOHUIZu9/EeJF0dVa8Bb2IeTF4e3T9yxNjG+76+Er/3znLOuzmdRHmtFnX/uyJQM7qWiuett61Lcc+C5Q2K7U/MQU9DvGKAJ67XXNeacR2smY8aw5U1CVhU5SIkPmDyAlCG0IprOUdbAxLZ6GJ51GcqML7eBxUOkb8AWaH7jP1xkaCAWD6/7wVYVUrJuSg1W4bJ8DC5UgMGDpCDM2VA/+ssA7EzNWKeI/O2DTgkX4GDU8ZVntBB9N4db7kOHnF5qvc2fADNhSUx2fOkahNiDjyVt+a6XfAOIGtO/adfWnP/lBx708E1cdcTNHH0vf5vvXDYmtAjH7awWzAedcOxAS+qq7btbG/k2YBVRiAV/kGhOXBhDbMs6dopgbGl1KoDzt7MbyZhmdFy3+j/38EgMnHy6CPXuwqPWq76sgOcOqzF+7gC0jjlW646DExkbIBP49IDE+1057yUXTUVQSc4++IEmaopHciZ67ZccB1Rg2uHovCYmYZc3v+0QwZk9RWPAMbQAPUL4lYQeTw4I6h5shXb9lTPnKECMQyUb2pHfVk0BYIp/LohxpOs31fsBdVkyPy8SiUaSxGOFy6bdf73cELLu1tXKD382axINA98r5N/nxFOnBW7l+DTkAobfq/XrTHRXd1om9kLiog=
  - secure: pbIFiqdPAOyiZ3B+E15JfZKN30jHghM479buNTvNY+juiq7c3CSOxQlsLOZy3ygDHuIM8cKSzhT8lqziSl76yJD4lyc91KA9Zd+osYK6fumbBj+0D2BXjIRWOgebL5V4krphf9Z5ATeUUdjg71k+B/2n5VVW3dkRVUcmwD0JKk2b4q9DVofojrs1FdBz7ayt04nT8JdPtSZPjfYyEm/SWDtEszLLejO9GmpnLGpyEpu1TR5kg7Te+Mrg0DdKCC0/aq2YC+YYd6Vyfps6vEXlRe3uhtddS//O2ZCjC2Tr8TlB5ggOAtL5FwA7aAiyo1kGbs2qvoRJu1V4ZRnUk3M6lU8S71lzrA+M9cJ8IkZQFvEpPhZ9E40zLSXSdxRBQKkPmhW+vzXT8SJwIUt97EJ0EihCIwkIDasS4yCkXIvAkw+KSIDoBXrA7IR1WlGfuHB+cFHzsxl9kVTsSWRjdN/vzikPHb8BFFgf0DrUkCc0rWaeP/tHY9Z7IZvo8RKvTdyGbAheX2XNiHcWHBp9KL2hgzMXRM2ppCZtd3A+DRHbywnO9xEIiCVGEGpMYM7WU4ZeDTwiKnxo2Wu5/Vz3OIGfxodappP0mOiTvYorjBkocb8d8iKfJL31YwJKoxN7RnbMcAnN/AS/I7Ykt/JUyQzhzYMfpAixNhOTuJdqO9t48yM=
before_cache:
- rm -rf $HOME/.m2/repository/ch/admin/seco/alv-portal-*
cache:
  directories:
  - "$HOME/.m2"
  - alv-portal-ui/node_modules
install:
- ".ci-travis/install-nodejs.sh ${NODE_VERSION}"
- ".ci-travis/install-chrome.sh"
script:
- export BRANCH_VERSION_SUFFIX=$([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo
  "-${TRAVIS_BRANCH//\//-}")
- export BUILD_VERSION=$PROJECT_VERSION-build-$TRAVIS_BUILD_NUMBER$BRANCH_VERSION_SUFFIX
- ".ci-travis/maven-set-version.sh ${BUILD_VERSION}"
deploy:
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-package.sh"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^release.*$"
- provider: script
  skip_cleanup: true
  script: ".ci-travis/maven-e2e.sh"
  on:
    all_branches: true
    condition: "$TRAVIS_EVENT_TYPE == cron"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
