version: '3.3'

services:
  alv-portal-webapp:
    image: "alvch-dockerv2-local.jfrog.io/alvch/alv-portal-webapp:${project.version}"
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    - SPRING.CLOUD.CONFIG.URI=http://admin:${jhipster.registry.password}@dev.job-room:8761/config
    ports:
    - 8899:8080
    secrets:
    - source: bootstrap.yml-1
      target: bootstrap.yml

secrets:
  bootstrap.yml-1:
    external: true
