version: '3.3'

services:
  alv-portal-webapp:
    image: "alvch-dockerv2-local.jfrog.io/alvch/alv-portal-webapp:${project.version}"
    env_file: env.properties
    networks:
    - jobroom_data2
    ports:
    - 8899:8080
    secrets:
    - source: bootstrap.yml-1
      target: bootstrap.yml

secrets:
  bootstrap.yml-1:
    external: true


networks:
  jobroom_data2:
    external: true
